version: '2'

services:
  redis: # Name of container
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - shared-network
  postgres: # Name of container
    image: postgres:alpine
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 5432:5432
    networks:
      - shared-network
  api:
    image: hou27/bookmark_backend:0.1.1
    networks:
      - shared-network
    env_file:
      - .env.prod
    ports:
      - 4000:4000
    depends_on:
      - redis
      - postgres
networks:
  shared-network:
    driver: bridge
