name: Deploy to EC2
on:
  push:
    branches: ['develop']

jobs:
  build:
    name: Build
    runs-on: quickchive-server
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY_PAIR }}
          script: |
            sh /home/ubuntu/actions-runner/deploy.sh
